"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

import django_heroku

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%wpod#qmq6uvmxpwd(e*@hkw^9394dzhhpc&t0_b9_!m8lik$u'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['uknews.herokuapp.com']


DEBUG = False



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # project app
    'mailer.subscribe.apps.SubscribeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # whitenoise to serve staticfiles in production : http://whitenoise.evans.io/en/stable/
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Try to connect to live database for a development project (continous development & deployment)
'''
> from heroku cli, type:

    heroku pg:credentials:url
                    OR 
        
    click on your database on heroku & go to
    https://data.heroku.com/datastores/8735f520-60fc-4dbe-9f90-a17a8338d53a#administration

Host : ec2-44-198-80-194.compute-1.amazonaws.com (<HOST>)
Database : d4ce8nnrmblv7m (<DATABASE_NAME>)
User : flyukiacpdacsg (<USER>)
Port : 5432 (<PORT>)
Password : 3b3124eae94d877956fe06cebb6679aed27a22be37b7b1b25ee972dbaab9f8af (<PASSWORD>)
URI : postgres://flyukiacpdacsg:3b3124eae94d877956fe06cebb6679aed27a22be37b7b1b25ee972dbaab9f8af@ec2-44-198-80-194.compute-1.amazonaws.com:5432/d4ce8nnrmblv7m
Heroku CLI : heroku pg:psql postgresql-graceful-17657 --app uknews


output:

"dbname=d4ce8nnrmblv7m host=ec2-44-198-80-194.compute-1.amazonaws.com port=5432 user=flyukiacpdacsg password=3b3124eae94d877956fe06cebb6679aed27a22be37b7b1b25ee972dbaab9f8af sslmode=require"
Connection URL:
   postgres://flyukiacpdacsg:3b3124eae94d877956fe06cebb6679aed27a22be37b7b1b25ee972dbaab9f8af@ec2-44-198-80-194.compute-1.amazonaws.com:5432/d4ce8nnrmblv7m

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd4ce8nnrmblv7m',
        'USER': 'flyukiacpdacsg',
        'PASSWORD': '3b3124eae94d877956fe06cebb6679aed27a22be37b7b1b25ee972dbaab9f8af',
        'HOST': 'ec2-44-198-80-194.compute-1.amazonaws.com',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'


STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

# whitenoise config. for staticfiles
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Config.

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'edd.edwardmike@gmail.com'
EMAIL_HOST_PASSWORD = 'xzulhnorwpasexwa'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'edd.edwardmike@gmail.com'


SITE_DOMAIN = 'uknews.herokuapp.com'



# Celery Config.
REDIS_TLS_URL = 'rediss://:pee1b408c7d288dca1d579a7c35cf1d35faaf546857dd8c75512ed9b1abd5fc7b@ec2-3-214-185-114.compute-1.amazonaws.com:27100'
REDIS_URL = 'redis://:pee1b408c7d288dca1d579a7c35cf1d35faaf546857dd8c75512ed9b1abd5fc7b@ec2-3-214-185-114.compute-1.amazonaws.com:27099'
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# heroku config
django_heroku.settings(locals())